const String baseURL = 'https://dontwaitapp.co/api',
    kSignUpOld = '/subscriber/signup',
    kSignUp = '/subscriber/signupfirebase',
    kSignIn = '/subscriber/login',
    signInotpUrl = '/subscriber/loginfirebase',
    kProfile = '/subscriber/profile',
    kAccessToken = '/subscriber/accesstoken',
    kSignOut = '/subscriber/logout',
    kCreateQueue = '/subscriber/createqueue',
    kViewAllQueues = '/subscriber/viewallqueues',
    kViewQueue = '/subscriber/viewqueue',
    kCancelQueue = '/subscriber/cancelqueue',
    kStartQueue = '/subscriber/startqueue',
    kNextQueue = '/subscriber/nextqueue',
    kEndQueue = '/subscriber/endQueue',
    kGetUser = '/subscriber/getuser',
    kGetQueueUser = '/subscriber/getqueueuser';
    const String fcmUrl = '/subscriber/fcm';
    
